name             'yum-nvidia'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
source_url       'https://github.com/osuosl-cookbooks/yum-nvidia'
issues_url       'https://github.com/osuosl-cookbooks/yum-nvidia/issues'
license          'Apache-2.0'
chef_version     '>= 14.0'
description      'Installs/Configures yum-nvidia'
long_description 'Installs/Configures yum-nvidia'
version          '1.1.1'

supports         'centos', '~> 8.0'
supports         'centos', '~> 7.0'
